services:
  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "5000:5000"    # on expose 5000→5000
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: ./frontend
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  gateway:
    build: ./gateway
    env_file: ./gateway/.env
    ports:
      - "8080:5000"    # host 8080 → container 5000
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
