apiVersion: apps/v1
kind: Deployment
metadata:
  name: progweb-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progweb-backend
  template:
    metadata:
      labels:
        app: progweb-backend
    spec:
      containers:
        - name: progweb-backend
          image: adsolt/progweb-backend:latest
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/progwebdb
            - name: JWT_SECRET
              value: supersecret123
---
apiVersion: v1
kind: Service
metadata:
  name: progweb-backend
spec:
  selector:
    app: progweb-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
