apiVersion: apps/v1
kind: Deployment
metadata:
  name: progweb-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progweb-frontend
  template:
    metadata:
      labels:
        app: progweb-frontend
    spec:
      containers:
        - name: progweb-frontend
          image: adsolt/progweb-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: progweb-frontend
spec:
  selector:
    app: progweb-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: NodePort
